# Исследование надежности заемщиков

Во второй части проекта вы выполните шаги 3 и 4. Их вручную проверит ревьюер.
Чтобы вам не пришлось писать код заново для шагов 1 и 2, мы добавили авторские решения в ячейки с кодом.

## Откройте таблицу и изучите общую информацию о данных

**Задание 1. Импортируйте библиотеку pandas. Считайте данные из csv-файла в датафрейм и сохраните в переменную `data`. Путь к файлу:**

`/datasets/data.csv`

In [1]:
import pandas as pd

try:
    data = pd.read_csv('/datasets/data.csv')
except:
    data = pd.read_csv('C:/Users/evgen/Documents/data/Проекты по аналитике Яндекс/Данные для проектов/Надежность заемщиков/data.csv')

**Задание 2. Выведите первые 20 строчек датафрейма `data` на экран.**

In [2]:
data.head(20)

,children,days_employed,dob_years,education,education_id,family_status,family_status_id,gender,income_type,debt,total_income,purpose
0,1,-8437.673028,42,высшее,0,женат / замужем,0,F,сотрудник,0,253875.639453,покупка жилья
1,1,-4024.803754,36,среднее,1,женат / замужем,0,F,сотрудник,0,112080.014102,приобретение автомобиля
2,0,-5623.422610,33,Среднее,1,женат / замужем,0,M,сотрудник,0,145885.952297,покупка жилья
3,3,-4124.747207,32,среднее,1,женат / замужем,0,M,сотрудник,0,267628.550329,дополнительное образование
4,0,340266.072047,53,среднее,1,гражданский брак,1,F,пенсионер,0,158616.077870,сыграть свадьбу
5,0,-926.185831,27,высшее,0,гражданский брак,1,M,компаньон,0,255763.565419,покупка жилья
6,0,-2879.202052,43,высшее,0,женат / замужем,0,F,компаньон,0,240525.971920,операции с жильем
7,0,-152.779569,50,СРЕДНЕЕ,1,женат / замужем,0,M,сотрудник,0,135823.934197,образование
8,2,-6929.865299,35,ВЫСШЕЕ,0,гражданский брак,1,F,сотрудник,0,95856.832424,на проведение свадьбы
9,0,-2188.756445,41,среднее,1,женат / замужем,0,M,сотрудник,0,144425.938277,покупка жилья для семьи
10,2,-4171.483647,36,высшее,0,женат / замужем,0,M,компаньон,0,113943.491460,покупка недвижимости
11,0,-792.701887,40,среднее,1,женат / замужем,0,F,сотрудник,0,77069.234271,покупка коммерческой недвижимости
12,0,NaN,65,среднее,1,гражданский брак,1,M,пенсионер,0,NaN,сыграть свадьбу
13,0,-1846.641941,54,неоконченное высшее,2,женат / замужем,0,F,сотрудник,0,130458.228857,приобретение автомобиля
14,0,-1844.956182,56,высшее,0,гражданский брак,1,F,компаньон,1,165127.911772,покупка жилой недвижимости
15,1,-972.364419,26,среднее,1,женат / замужем,0,F,сотрудник,0,116820.904450,строительство собственной недвижимости
16,0,-1719.934226,35,среднее,1,женат / замужем,0,F,сотрудник,0,289202.704229,недвижимость
17,0,-2369.999720,33,высшее,0,гражданский брак,1,M,сотрудник,0,90410.586745,строительство недвижимости
18,0,400281.136913,53,среднее,1,вдовец / вдова,2,F,пенсионер,0,56823.777243,на покупку подержанного автомобиля
19,0,-10038.818549,48,СРЕДНЕЕ,1,в разводе,3,F,сотрудник,0,242831.107982,на покупку своего автомобиля

**Задание 3. Выведите основную информацию о датафрейме с помощью метода `info()`.**

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   children          21525 non-null  int64
 1   days_employed     19351 non-null  float64
 2   dob_years         21525 non-null  int64
 3   education         21525 non-null  object
 4   education_id      21525 non-null  int64
 5   family_status     21525 non-null  object
 6   family_status_id  21525 non-null  int64
 7   gender            21525 non-null  object
 8   income_type       21525 non-null  object
 9   debt              21525 non-null  int64
 10  total_income      19351 non-null  float64
 11  purpose           21525 non-null  object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB

## Предобработка данных

### Удаление пропусков

**Задание 4. Выведите количество пропущенных значений для каждого столбца. Используйте комбинацию двух методов.**

In [4]:
data.isna().sum()

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64

**Задание 5. В двух столбцах есть пропущенные значения. Один из них — `days_employed`. Пропуски в этом столбце вы обработаете на следующем этапе. Другой столбец с пропущенными значениями — `total_income` — хранит данные о доходах. На сумму дохода сильнее всего влияет тип занятости, поэтому заполнить пропуски в этом столбце нужно медианным значением по каждому типу из столбца `income_type`. Например, у человека с типом занятости `сотрудник` пропуск в столбце `total_income` должен быть заполнен медианным доходом среди всех записей с тем же типом.**

In [5]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['total_income'].isna()), 'total_income'] = \
    data.loc[(data['income_type'] == t), 'total_income'].median()

### Обработка аномальных значений

**Задание 6. В данных могут встречаться артефакты (аномалии) — значения, которые не отражают действительность и появились по какой-то ошибке. таким артефактом будет отрицательное количество дней трудового стажа в столбце `days_employed`. Для реальных данных это нормально. Обработайте значения в этом столбце: замените все отрицательные значения положительными с помощью метода `abs()`.**

In [6]:
data['days_employed'] = data['days_employed'].abs()

**Задание 7. Для каждого типа занятости выведите медианное значение трудового стажа `days_employed` в днях.**

In [7]:
data.groupby('income_type')['days_employed'].agg('median')

income_type
безработный        366413.652744
в декрете            3296.759962
госслужащий          2689.368353
компаньон            1547.382223
пенсионер          365213.306266
предприниматель       520.848083
сотрудник            1574.202821
студент               578.751554
Name: days_employed, dtype: float64

У двух типов (безработные и пенсионеры) получатся аномально большие значения. Исправить такие значения сложно, поэтому оставьте их как есть.

**Задание 8. Выведите перечень уникальных значений столбца `children`.**

In [8]:
data['children'].unique()

array([ 1,  0,  3,  2, -1,  4, 20,  5])

**Задание 9. В столбце `children` есть два аномальных значения. Удалите строки, в которых встречаются такие аномальные значения из датафрейма `data`.**

In [9]:
data = data[(data['children'] != -1) & (data['children'] != 20)]

**Задание 10. Ещё раз выведите перечень уникальных значений столбца `children`, чтобы убедиться, что артефакты удалены.**

In [10]:
data['children'].unique()

array([1, 0, 3, 2, 4, 5])

### Удаление пропусков (продолжение)

**Задание 11. Заполните пропуски в столбце `days_employed` медианными значениями по каждого типа занятости `income_type`.**

In [11]:
for t in data['income_type'].unique():
    data.loc[(data['income_type'] == t) & (data['days_employed'].isna()), 'days_employed'] = \
    data.loc[(data['income_type'] == t), 'days_employed'].median()

**Задание 12. Убедитесь, что все пропуски заполнены. Проверьте себя и ещё раз выведите количество пропущенных значений для каждого столбца с помощью двух методов.**

In [12]:
data.isna().sum()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

### Изменение типов данных

**Задание 13. Замените вещественный тип данных в столбце `total_income` на целочисленный с помощью метода `astype()`.**

In [13]:
data['total_income'] = data['total_income'].astype(int)

### Обработка дубликатов

**Задание 14. Обработайте неявные дубликаты в столбце `education`. В этом столбце есть одни и те же значения, но записанные по-разному: с использованием заглавных и строчных букв. Приведите их к нижнему регистру.**

In [14]:
data['education'] = data['education'].str.lower()

**Задание 15. Выведите на экран количество строк-дубликатов в данных. Если такие строки присутствуют, удалите их.**

In [15]:
data.duplicated().sum()

71

In [16]:
data = data.drop_duplicates()

### Категоризация данных

**Задание 16. На основании диапазонов, указанных ниже, создайте в датафрейме `data` столбец `total_income_category` с категориями:**

- 0–30000 — `'E'`;
- 30001–50000 — `'D'`;
- 50001–200000 — `'C'`;
- 200001–1000000 — `'B'`;
- 1000001 и выше — `'A'`.


**Например, кредитополучателю с доходом 25000 нужно назначить категорию `'E'`, а клиенту, получающему 235000, — `'B'`. Используйте собственную функцию с именем `categorize_income()` и метод `apply()`.**

In [17]:
def categorize_income(income):
    try:
        if 0 <= income <= 30000:
            return 'E'
        elif 30001 <= income <= 50000:
            return 'D'
        elif 50001 <= income <= 200000:
            return 'C'
        elif 200001 <= income <= 1000000:
            return 'B'
        elif income >= 1000001:
            return 'A'
    except:
        pass

In [18]:
data['total_income_category'] = data['total_income'].apply(categorize_income)

**Задание 17. Выведите на экран перечень уникальных целей взятия кредита из столбца `purpose`.**

In [19]:
data['purpose'].unique()

array(['покупка жилья', 'приобретение автомобиля',
       'дополнительное образование', 'сыграть свадьбу',
       'операции с жильем', 'образование', 'на проведение свадьбы',
       'покупка жилья для семьи', 'покупка недвижимости',
       'покупка коммерческой недвижимости', 'покупка жилой недвижимости',
       'строительство собственной недвижимости', 'недвижимость',
       'строительство недвижимости', 'на покупку подержанного автомобиля',
       'на покупку своего автомобиля',
       'операции с коммерческой недвижимостью',
       'строительство жилой недвижимости', 'жилье',
       'операции со своей недвижимостью', 'автомобили',
       'заняться образованием', 'сделка с подержанным автомобилем',
       'получение образования', 'автомобиль', 'свадьба',
       'получение дополнительного образования', 'покупка своего жилья',
       'операции с недвижимостью', 'получение высшего образования',
       'свой автомобиль', 'сделка с автомобилем',
       'профильное образование', 'высшее образование',
       'покупка жилья для сдачи', 'на покупку автомобиля', 'ремонт жилью',
       'заняться высшим образованием'], dtype=object)

**Задание 18. Создайте функцию, которая на основании данных из столбца `purpose` сформирует новый столбец `purpose_category`, в который войдут следующие категории:**

- `'операции с автомобилем'`,
- `'операции с недвижимостью'`,
- `'проведение свадьбы'`,
- `'получение образования'`.

**Например, если в столбце `purpose` находится подстрока `'на покупку автомобиля'`, то в столбце `purpose_category` должна появиться строка `'операции с автомобилем'`.**

**Используйте собственную функцию с именем `categorize_purpose()` и метод `apply()`. Изучите данные в столбце `purpose` и определите, какие подстроки помогут вам правильно определить категорию.**

In [20]:
def categorize_purpose(row):
    try:
        if 'автом' in row:
            return 'операции с автомобилем'
        elif 'жил' in row or 'недвиж' in row:
            return 'операции с недвижимостью'
        elif 'свад' in row:
            return 'проведение свадьбы'
        elif 'образов' in row:
            return 'получение образования'
    except:
        return 'нет категории'

In [21]:
data['purpose_category'] = data['purpose'].apply(categorize_purpose)

### Шаг 3. Исследуйте данные и ответьте на вопросы

#### 3.1 Есть ли зависимость между количеством детей и возвратом кредита в срок?

In [22]:
# Сгруппируем данные по количеству детей и посчитаем сколько клиентов в каждой группе не вернули кредит в срок.
data.groupby('children')['debt'].sum()

children
0    1063
1     444
2     194
3      27
4       4
5       0
Name: debt, dtype: int64

In [23]:
# Посчитаем сколько всего клиентов в каждой группе
data.groupby('children')['debt'].count()

children
0    14091
1     4808
2     2052
3      330
4       41
5        9
Name: debt, dtype: int64

In [24]:
# Найдем отношение просрочек по кредиту к общему количеству по каждой группе
(data.groupby('children')['debt'].sum())/(data.groupby('children')['debt'].count()) * 100

children
0    7.543822
1    9.234609
2    9.454191
3    8.181818
4    9.756098
5    0.000000
Name: debt, dtype: float64

**Вывод:**

Зависимость между количеством детей и возвратом кредита есть: из всех клиентов без детей задолженность есть только у 7,54%. Среди клиентов с детьми чаще всего допускают просрочку те, у кого четверо детей (9,76%). Возвращают кредит в срок клиенты с тремя детьми - 8,18%. 
Клиенты с пятью детьми вернули кредит в срок, но данная выборка не совсем верна, так как таких семей всего 9.

#### 3.2 Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [25]:
# Сгруппируем данные по семейному статусу и посчитаем сколько клиентов в каждой группе не вернули кредит в срок.
data.groupby('family_status')['debt'].sum()

family_status
Не женат / не замужем    273
в разводе                 84
вдовец / вдова            63
гражданский брак         385
женат / замужем          927
Name: debt, dtype: int64

In [26]:
# Посчитаем сколько всего клиентов в каждой группе
data.groupby('family_status')['debt'].count()

family_status
Не женат / не замужем     2796
в разводе                 1189
вдовец / вдова             951
гражданский брак          4134
женат / замужем          12261
Name: debt, dtype: int64

In [27]:
# Найдем отношение просрочек по кредиту к общему количеству клиентов в каждой группе
(data.groupby('family_status')['debt'].sum())/(data.groupby('family_status')['debt'].count()) * 100

family_status
Не женат / не замужем    9.763948
в разводе                7.064760
вдовец / вдова           6.624606
гражданский брак         9.313014
женат / замужем          7.560558
Name: debt, dtype: float64

In [28]:
# группировка данных по семейному статусу и нахождение доли должников в группах методом agg()
data.groupby('family_status').agg({'debt': ['sum', 'count', 'mean']})

                      debt
                       sum  count      mean
family_status
Не женат / не замужем  273   2796  0.097639
в разводе               84   1189  0.070648
вдовец / вдова          63    951  0.066246
гражданский брак       385   4134  0.093130
женат / замужем        927  12261  0.075606

**Вывод:**

Наибольшее количество просрочек по кредиту среди не женатых (9,76%) и живущих гражданским браком (9,31%). Наиболее ответственно относятся к выплате кредита в срок вдовцы - 6,62%. Среди женатых клиентов не возвращают кредит в срок 7,56%. Клиенты находящиеся в разводе нарушают срок выплат по кредиту в 7,06% случаев.

Низкий процент просрочек по кредиту среди вдовцов можно объяснить тем, что чаще это люди в возрасте. Так же у них уже могут быть собственные взрослые дети, которые помогают с платежами. А если они еще работают, то их карьера сложилась и заработок стабильный.

Верятными причинами большого количества просрочек среди не женатых можно назвать низкий возраст и, как следствие, начальные этапы карьеры с не большим заработком.

#### 3.3 Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [29]:
# Сгруппируем данные по категории дохода и посчитаем сколько клиентов в каждой группе не вернули кредит в срок.
data.groupby('total_income_category')['debt'].sum()

total_income_category
A       2
B     354
C    1353
D      21
E       2
Name: debt, dtype: int64

In [30]:
# Посчитаем сколько всего клиентов в каждой группе
data.groupby('total_income_category')['debt'].count()

total_income_category
A       25
B     5014
C    15921
D      349
E       22
Name: debt, dtype: int64

In [31]:
# Найдем отношение просрочек по кредиту к общему количеству клиентов в каждой группе
(data.groupby('total_income_category')['debt'].sum())/(data.groupby('total_income_category')['debt'].count()) * 100

total_income_category
A    8.000000
B    7.060231
C    8.498210
D    6.017192
E    9.090909
Name: debt, dtype: float64

**Вывод:**

Явной зависимости не обнаружено. Количество клиентов в категориях дохода A, D, E не достаточно для объективного определения зависимости между уровнем дохода и возвратом кредита в срок. Среди клиентов в остальных категориях количество просрочек меньше у клиентов в категории дохода В (200000-1000000) - 7,06%.

#### 3.4 Как разные цели кредита влияют на его возврат в срок?

In [32]:
# группировка данных по цели кредита и нахождение доли должников в группах с помощью сводной таблицы
data_pivot = data.pivot_table(
    index='purpose_category',
    values='debt',
    aggfunc={'debt': ['sum', 'count', 'mean']}
    )
data_pivot

                            count      mean    sum
purpose_category
операции с автомобилем     4279.0  0.093480  400.0
операции с недвижимостью  10751.0  0.072551  780.0
получение образования      3988.0  0.092528  369.0
проведение свадьбы         2313.0  0.079118  183.0

**Вывод:**

Лучше всего возвращают в срок кредит на недвижимость - 7,25%. Больше всего просрочек среди операций с автомобилем - 9,35%. Чуть ответственнее автомобилистов те клиенты, что брали кредит на образование - 9,25%. Среди тех кто брал кредит на проведение свадьбы количество просрочек равно 7,91%.

#### 3.5 Приведите возможные причины появления пропусков в исходных данных.

*Ответ:* 
В пропущенных значениях была важная для получения кредита информация - данные о трудовом стаже и ежемесячном доходе. Поэтому можно предположить что данные были потеряны случайно - при копировани или переносе.

#### 3.6 Объясните, почему заполнить пропуски медианным значением — лучшее решение для количественных переменных.

*Ответ:* 
В столбцах с пропусками могут быть значения которые сильно выделяются среди большинства. Если вместо медианного значения заполнить пропуски средними данные могут исказиться. Если выделяющихся значений нет, то медиана будет очень близка к среднему.

### Шаг 4: общий вывод.

Напишите ваш общий вывод.

В ходе исследования надежности заемщиков были изучены данные статистики о платежеспособности клиентов, удалены дубликаты, заполнены пропуски, клиенты объеденены по новым категориям. По результатам работы ответы на поставленные вопросы следующие:
* **Есть ли зависимость между семейным положением и возвратом кредита в срок?**
  Зависимость между количеством детей и возвратом кредита есть: из всех клиентов без детей задолженность есть только у 7,54%. Среди клиентов с детьми чаще всего допускают просрочку те, у кого четверо детей (9,76%). Возвращают кредит в срок клиенты с тремя детьми - 8,18%. Клиенты с пятью детьми вернули кредит в срок, но данная выборка не совсем верна, так как таких семей всего 9.
* **Есть ли зависимость между семейным положением и возвратом кредита в срок?**
  Зависимость есть. Наибольшее количество просрочек по кредиту среди не женатых (9,76%) и живущих гражданским браком (9,31%). Наиболее ответственно относятся к выплате кредита в срок вдовцы - 6,62%. Среди женатых клиентов не возвращают кредит в срок 7,56%. Клиенты находящиеся в разводе нарушают срок выплат по кредиту в 7,06% случаев.
* **Есть ли зависимость между уровнем дохода и возвратом кредита в срок?**
  Явной зависимости не обнаружено. Количество клиентов в категориях дохода A, D, E не достаточно для объективного определения зависимости между уровнем дохода и возвратом кредита в срок. Среди клиентов в остальных категориях количество просрочек меньше у клиентов в категории дохода В (200000-1000000) - 7,06%.
* **Как разные цели кредита влияют на его возврат в срок?**
  Лучше всего возвращают в срок кредит на недвижимость - 7,25%. Больше всего просрочек среди операций с автомобилем - 9,35%. Чуть ответственнее автомобилистов те клиенты, что брали кредит на образование - 9,25%. Среди тех кто брал кредит на проведение свадьбы количество просрочек равно 7,91%.

------
Рекомендации компании

Компании рекомендуется при построении модели кредитного скролинга уделить внимание количеству детей клиента и его семейному положению. Для более подробного изучения зависимости уровня дохода и возврата кредита в срок возможно стоит пересмотреть установленные категории дохода.

<span style="color:green">**Дополнение к выводу:**</span>

Компании рекомендуется при построении модели кредитного скролинга уделить внимание количеству детей клиента и его семейному положению. Для более подробного изучения зависимости уровня дохода и возврата кредита в срок возможно стоит пересмотреть установленные категории дохода.